apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "MySQLRootPass123!"
  MYSQL_DATABASE: "phpapp"
  MYSQL_USER: "phpuser"
  MYSQL_PASSWORD: "MySQLUserPass123!"
